title: Currency Converter
description: This is the technical documentation of the Currency Converter
remote_theme: pmarsceill/just-the-docs

domain: kannadev.com
url: kannadev.com
baseurl: /converter-py-college/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
