source 'https://rubygems.org'

#gem "jekyll", "~> 4.3" # installed by `gem jekyll`
gem "github-pages", "~> 3.9.2", group: :jekyll_plugins

# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs" # currently the latest pre-release
# gem "just-the-docs"            # the latest release - currently 0.3.3
